// examples/basic-render-test/src/main.ts
import './style.css';
import init, { create_app_node } from 'rusty-react';

async function run() {
  // First, we need to initialize our Wasm module.
  // The 'init' function is auto-generated by wasm-pack.
  await init();

  // Now we can call our exported Rust function!
  const appNode = create_app_node();

  // Let's see what we got from Rust.
  // This will be the JavaScript object version of our Rust structs.
  console.log('Virtual DOM node received from Rust:', appNode);

  // For fun, let's render it as a string to the page.
  const appDiv = document.querySelector<HTMLDivElement>('#app')!;
  appDiv.innerHTML = `
    <h1>Check the Browser Console!</h1>
    <pre><code>${JSON.stringify(appNode, null, 2)}</code></pre>
  `;
}

run();
